inherit_from:
  - .rubocop_airbnb.yml

Rails:
  Enabled: true

AllCops:
  Exclude:
    - 'bin/**'
    - 'config/**/*'
    - 'db/**/*'
    - 'vendor/**/**/*'
    - 'spec/*'
    - 'spec/system/**'
Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Layout/FirstHashElementLineBreak:
  Enabled: false

Airbnb/OptArgParameters:
  Enabled: false

Style/ColonMethodCall:
  Enabled: false

Layout/IndentationConsistency:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Rails/HelperInstanceVariable:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Style/MultilineTernaryOperator:
  Enabled: false

Airbnb/DefaultScope:
  Enabled: false

Lint/UselessAssignment:
  Exclude:
    - 'app/uploaders/*'

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Layout/FirstArrayElementLineBreak:
  Enabled: false

Airbnb/RiskyActiverecordInvocation:
  Enabled: false

Airbnb/ModuleMethodInWrongFile:
  Description: Define a module method in the file that defines the module, not a file that
    happens to use the module as a namespace.
  Enabled: false
  Include:
    - 'app/**/*'
    - 'lib/**/*'
